import { jsPDF } from 'jspdf';
import 'jspdf-autotable'; // Import AutoTable plugin for table layout
import dayjs from 'dayjs';

/**
 * Generates a beautiful PDF with a styled title and a clean table layout.
 * @param {Array} messages - Array of message objects to include in the PDF.
 * @param {string} username - Current user's username.
 */
export const genratePDF = (messages, username) => {
  const doc = new jsPDF();

  // Gradient Title Simulation
  const gradientColors = ['#7D4FBD', '#F472B6', '#F87171']; // Purple, Pink, Red
  const titleText = 'True Feedback';
  let currentX = 10;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(30);

  for (let i = 0; i < titleText.length; i++) {
    doc.setTextColor(gradientColors[i % gradientColors.length]);
    doc.text(titleText[i], currentX, 20); // Each character is placed sequentially
    currentX += doc.getTextWidth(titleText[i]); // Adjust position for next character
  }

  // Add Subtitle
  doc.setFontSize(12);
  doc.setTextColor('#000000');
  doc.text(
    'A report summarizing user messages, their ratings, and timestamps.',
    10,
    30
  );

  // Add a Divider
  doc.setDrawColor(200, 200, 200); // Light grey
  doc.line(10, 35, 200, 35); // Draw a horizontal line

  // Prepare Table Data
  const tableData = messages.map((message) => [
    message._id,
    message.content,
    message.rating,
    dayjs(message.createdAt).format('MMM D, YYYY h:mm A'),
  ]);

  // Add Table using AutoTable
  doc.autoTable({
    head: [['ID', 'Content', 'Rating', 'Date']], // Table header
    body: tableData,
    startY: 40, // Start below the subtitle
    theme: 'grid', // Use grid theme for modern look
    headStyles: {
      fillColor: [125, 79, 189], // Purple gradient start
      textColor: '#FFFFFF',
      fontSize: 12,
    },
    bodyStyles: {
      fontSize: 10,
      textColor: '#333333',
      halign: 'center', // Align text in the center if necessary
      valign: 'middle',
      lineWidth: 0.5,
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245], // Light grey for alternate rows
    },
    styles: {
      cellPadding: 5,
    },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 'auto' },
      3: { cellWidth: 'auto' },
    },
    tableWidth: 'auto',
  });

  // Add Footer
  const pageCount = doc.internal.getNumberOfPages(); // Get total page count
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor('#999999');
    doc.text(`Page ${i} of ${pageCount}`, 10, 290); // Footer on each page
    doc.text('Generated by True Feedback', 150, 290, { align: 'right' }); // Footer branding
  }

  const sanitizedUsername = username.replace(/[^a-zA-Z0-9_-]/g, ''); // Sanitize username for file name
  doc.save(`${sanitizedUsername}_TrueFeedback_Report.pdf`);
};
