import dayjs from 'dayjs';

/**
 * Generates the HTML content for the PDF.
 * @param {Array} messages - Array of message objects to include in the HTML.
 * @returns {string} - HTML string.
 */
export const generateHTMLContent = (messages) => `
  <div style="font-family: Arial, sans-serif; color: #333; max-width: 800px; margin: 0 auto; padding: 20px;">
    <h1 style="font-size: 28px; background: -webkit-linear-gradient(45deg, #7D4FBD, #F472B6, #F87171); -webkit-background-clip: text; -webkit-text-fill-color: transparent; text-align: center;">
      True Feedback
    </h1>
    <p style="font-size: 14px; text-align: center; margin-bottom: 20px;">
      A report summarizing user messages, their ratings, and timestamps.
    </p>
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
      <thead>
        <tr>
          <th style="border: 1px solid #ddd; padding: 8px; background-color: #7D4FBD; color: #fff; font-size: 14px;">ID</th>
          <th style="border: 1px solid #ddd; padding: 8px; background-color: #7D4FBD; color: #fff; font-size: 14px;">Content</th>
          <th style="border: 1px solid #ddd; padding: 8px; background-color: #7D4FBD; color: #fff; font-size: 14px;">Rating</th>
          <th style="border: 1px solid #ddd; padding: 8px; background-color: #7D4FBD; color: #fff; font-size: 14px;">Date</th>
        </tr>
      </thead>
      <tbody>
        ${messages
          .map(
            (message) => `
            <tr>
              <td style="border: 1px solid #ddd; padding: 8px; font-size: 12px;">${message._id}</td>
              <td style="border: 1px solid #ddd; padding: 8px; font-size: 12px;">${message.content}</td>
              <td style="border: 1px solid #ddd; padding: 8px; font-size: 12px;">${message.rating}</td>
              <td style="border: 1px solid #ddd; padding: 8px; font-size: 12px;">${dayjs(message.createdAt).format(
                'MMM D, YYYY h:mm A'
              )}</td>
            </tr>
          `
          )
          .join('')}
      </tbody>
    </table>
    <footer style="text-align: center; margin-top: 40px; font-size: 12px; color: #999;">
      Generated by True Feedback
    </footer>
  </div>
`;
